#!/bin/bash
# Launch a dmenu prompt to select which documentation item to view

choice=$(printf "vim\\nzsh\\ntmux" | dmenu -fn "Inconsolata-25")
groff -mom $HOME/.local/share/docs/$choice.mom -Tpdf | zathura -
